import { useRef } from 'react';
import Head from 'next/head';
import Avatar from '../components/avatar';
import { ViewGridIcon } from '@heroicons/react/solid';
import { MicrophoneIcon, SearchIcon } from '@heroicons/react/outline';
import Image from 'next/image';
import Footer from '../components/footer';
import { useRouter } from 'next/router';

export default function Home() {
  const router = useRouter();
  const searchInput = useRef(null);

  const handleSearch = (e) => {
    e.preventDefault();

    const term = searchInput.current.value;
    if (!term) return;
    router.push(`/search?term=${term}`);
  };

  return (
    <div className="flex flex-col items-center h-screen ">
      <Head>
        <title>Google</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* header */}

      <header className="flex w-full p-5 justify-between ">
        {/* left */}
        <div className="flex space-x-4 items-center font-semibold  text-sm text-gray-700 ">
          <p className="link">About</p>
          <p className="link">Store</p>
        </div>

        {/* right */}
        <div className="flex space-x-4 items-center font-semibold text-sm text-gray-700 ">
          <p className="link">Gmail</p>
          <p className="link ">Images</p>

          {/* icon */}
          <ViewGridIcon className="h-10 w-10 p-2 rounded-full hover:bg-gray-200 cursor-pointer text-blue-500" />

          {/* avatar */}
          <Avatar url="/PngItem_1468281.png" />
        </div>
      </header>

      {/* body */}
      <form
        action=""
        className="flex flex-col items-center mt-44 flex-grow w-4/5"
      >
        <Image
          src="https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png"
          alt="Google Logo"
          width={300}
          height={100}
        />
        <div className="flex items-center px-5 py-3 w-full mt-5 hover:shadow-lg  focus-within:shadow-lg max-w-md rounded-full border border-gray-200 sm:max-w-xl lg:max-w-2xl">
          <SearchIcon className="h-5 mr-3 text-gray-500" />
          <input
            ref={searchInput}
            type="text"
            className="flex-grow focus:outline-none   "
          />
          <MicrophoneIcon className="h-5 mr-3 text-gray-500" />
        </div>

        <div className="flex flex-col w-1/2  space-y-2 justify-center mt-8 sm:space-y-0 sm:flex-row sm:space-x-4">
          <button className="btn" onClick={handleSearch}>
            Google Search
          </button>
          <button className="btn" onClick={handleSearch}>
            I&apos;m Feeling Lucky
          </button>
        </div>
      </form>

      {/* footer */}
      <Footer />
    </div>
  );
}
